---
- name: Check if repo exists
  stat:
    path: "{{ app_dir }}/.git"
  register: repo_exists

- name: Clone or update repo
  git:
    repo: "{{ app_repo_url }}"
    dest: "{{ app_dir }}"
    update: "{{ repo_exists.stat.exists }}"
    force: yes
    version: "{{ app_branch }}"

- name: Create .env
  ansible.builtin.copy:
    dest: "{{ app_dir }}/.env"
    content: |
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD={{ postgres_password }}
      POSTGRES_DB=messages
      POSTGRES_HOST=postgres
      POSTGRES_PORT=5432
    mode: '0644'

- name: Run Docker Compose
  command: docker compose up -d --force-recreate 
  args:
    chdir: "{{ app_dir }}"