---  
- name: Ensure keyring directory exists
  file:
    path: "{{ docker_key_dir }}" 
    state: directory
    mode: 0755

- name: Check if Docker GPG key exists
  stat:
    path: "{{ docker_key_dir }}/docker-archive-keyring.gpg"
  register: docker_key_stat
  changed_when: false

- name: Download and convert Docker GPG key (if missing)
  command: >
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
    gpg --dearmor -o {{ docker_key_dir }}/docker-archive-keyring.gpg
  args:
    creates: "{{ docker_key_dir }}/docker-archive-keyring.gpg"
  when: not docker_key_stat.stat.exists

- name: Add Docker repository (secure way)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ docker_key_dir }}/docker-archive-keyring.gpg] \
          {{ docker_repo_url }} \
          {{ docker_repo_distribution }} \
          {{ docker_repo_component }}"
    state: present
    filename: docker

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Docker & Docker Compose (v2)
  apt:  
    name: "{{ docker_packages }}"
    state: present    
    update_cache: no

- name: Ensure Docker is running  
  service:  
    name: docker  
    state: started  
    enabled: yes  
